<a href="<?php echo App::config("url") ?>nastup/prepareadd" class="success button expanded">
    Dodaj novi nastup
</a>
<table>
    <thead>
        <tr>
            <th>Datum pocetka</th>
            <th>Cijena</th>
            <th>Adresa</th>
            <th>Vrsta svirke</th>
            <th>Bend</th>
            <th>Uredi/Obriši</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($nastupi as $nastup): ?>
        <tr>
            <td><?php echo $nastup->datumpocetka ?></td>
            <td><?php echo $nastup->cijena ?></td>
            <td><?php echo $nastup->adresa ?></td>
            <td><?php echo $nastup->vrstasvirke ?></td>  
            <td><?php echo $nastup->bend_nastup ?></td>

<!--            <td>-->
<!--            -->
<!--            <i class="fa--><?php //echo $smjer->verificiran ? "s" : "r" ?><!-- fa-check-square"></i>-->
<!--            -->
<!--            </td>-->
            <td> 
                <a href="<?php echo App::config("url") ?>nastup/prepareedit/<?php echo $nastup->sifra ?>">
                    <i style ="color:green;" class="fas fa-edit fa-2x"></i>
                </a>

                <?php if($nastup->ukupno==0): ?>
                    <a style="color: red;"
                     href="<?php echo App::config("url") ?>nastup/delete/<?php echo $nastup->sifra ?>">
                        <i class="fas fa-trash fa-2x"></i>
                    </a>
                <?php endif; ?>
            
             </td>
        </tr>
        <?php endforeach;?>
    </tbody>
</table>
<nav aria-label="Pagination">
  <ul class="pagination text-center">
    <li class="pagination-previous"><a href="<?php echo App::config("url") ?>nastup/index/<?php echo $prethodna ?>" aria-label="Next page">Prethodna <span class="show-for-sr">page</span></a></li>
    <li class="pagination-next"><a href="<?php echo App::config("url") ?>nastup/index/<?php echo $sljedeca ?>" aria-label="Next page">Sljedeća <span class="show-for-sr">page</span></a></li>
  </ul>
</nav>