<label>Datum početka
    <input type="text" name="datumpocetka" 
    value="<?php echo Request::post("datumpocetka") ?>" />
  </label>

  <label>Cijena
    <input type="text" name="cijena"
    value="<?php echo Request::post("cijena") ?>" />
  </label>

  <label>Adresa
    <input type="text" name="adresa"
    value="<?php echo Request::post("adresa") ?>" />
  </label>

  <label>Vrsta svirke
    <input type="text" name="vrstasvirke"
    value="<?php echo Request::post("vrstasvirke") ?>" />
  </label>

  <label for="bend">Bend</label>
    <select name="bend" id="bend">
    <option value="0">Odaberi bend</option>

    <?php foreach(Bend::read(1) as $bend): ?>      

    <option 

        <?php if(Request::post("bend")==$bend->sifra):?>
        selected="selected" 
        <?php endif;?>

        value="<?php echo $bend->sifra ?>"><?php echo $bend->naziv ?></option>

    <?php endforeach; ?>
    </select>
