<label>Datum početka
    <input type="text" name="datumpocetka" 
    value="<?php echo Request::post("datumpocetka") ?>" />
  </label>

  <label>Cijena
    <input type="text" name="cijena"
    value="<?php echo Request::post("cijena") ?>" />
  </label>

  <label>Adresa
    <input type="text" name="adresa"
    value="<?php echo Request::post("adresa") ?>" />
  </label>

  <label>Vrsta svirke
    <input type="text" name="vrstasvirke"
    value="<?php echo Request::post("vrstasvirke") ?>" />
  </label>

<label>Bend
    <input type="text" name="bend"
    value="<?php echo Request::post("bend") ?>" />
  </label>

