<label>Naziv
    <input type="text" name="naziv" 
    value="<?php echo Request::post("naziv") ?>" />
  </label>

  <label>Korisničko ime
    <input type="text" name="korisnickoime"
    value="<?php echo Request::post("korisnickoime") ?>" />
  </label>

  <label>Lozinka
    <input type="text" name="lozinka"
    value="<?php echo Request::post("lozinka") ?>" />
  </label>

  <label>Email
    <input type="text" name="email"
    value="<?php echo Request::post("email") ?>" />
  </label>

