    
  <label>Ime
    <input type="text" name="ime" 
    value="<?php echo Request::post("ime") ?>" />
  </label>
  <label>Prezime
    <input type="text" name="prezime" 
    value="<?php echo Request::post("prezime") ?>" />
  </label>
  <label>Email
    <input type="text" name="email" 
    value="<?php echo Request::post("email") ?>" />
  </label>
  <label>Bend
    <input type="number" name="bend" 
    value="<?php echo Request::post("bend") ?>" />
  </label>



