<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <?php include_once "head.phtml" ?>
  </head>
  <body>
    <div class="grid-container">

    <div class="grid-x">
        <div class="cell">
            <h1 style="width: 100%; text-align: center; padding-top:10px; text-transform: uppercase; color: #ffffff;"><?php echo App::config("nazivApp") ?></h1>
        </div>
    </div>

    <?php include_once "izbornik.phtml" ?>
       
        <div class="callout" style="min-height: 400px;">
            <?php echo $content ?>
           
        </div>
       
        <div class="<?php echo App::config("dev") ? "alert " : "" ?>callout">
           &copy; Evidencija svirki <?php echo date("Y") . (App::config("dev") ? " RAZVOJ " : "") ?>
        </div>




    </div>
    
    <script src="<?php echo App::config("url") ?>public/js/vendor/jquery.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/vendor/what-input.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/vendor/foundation.js"></script>
    <script src="<?php echo App::config("url") ?>public/js/app.js"></script>
  </body>
</html>