<form class="log-in-form" method="post" 
action="<?php echo App::config("url") ?>admin/login">

  <label>Email
    <input type="email" name="email" placeholder="leon.mikic93@gmail.com"
    value="<?php 
    if (isset($_POST[email])){
      echo Request::post("email");
    }else{
      echo App::config("dev") ? "leon.mikic93@gmail.com" : "";
    }
     ?>">
  </label>
  <label>Password
    <input type="password" name="password" placeholder="t" value="<?php 
    if (!isset($_POST[email])){
      echo App::config("dev") ? "t" : "";
    }
    ?>">
  </label>
 
  <p><input type="submit" class="button expanded" value="Log in" /></p>

</form>
<?php echo $poruka ?>


